package com.nusaregex.view;


import com.toedter.calendar.JDateChooser;
import com.nusaregex.controller.ControlAdmin;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
//import com.nusabank.view.viewAdmin.ViewMenuAdmin;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.filechooser.FileSystemView;

public class View extends javax.swing.JFrame {

    private ControlAdmin cma;
    /**
     * Creates new form View
     */
    private String fileName;
    private String sourcePath;
    private String destPath;
    
    public View() {
        initComponents();
        cma = new ControlAdmin(this);
        dcTglLahir.setDate(new Date());
    }
    
    
    public JTextArea getTxtAreaValidation() {
        return txtAreaValidation;
    }

    public JDateChooser getDcTglLahir() {
        return dcTglLahir;
    }

    public javax.swing.JComboBox<String> getCmbJenisKelamin() {
        return cmbJenisKelamin;
    }


    public javax.swing.JTextArea getTxtAlamatAdmin() {
        return tfAlamatAdmin;
    }

    public javax.swing.JTextField getTxtEmailAdmin() {
        return tfEmailAdmin;
    }

    public javax.swing.JTextField getTxtIdAdmin() {
        return tfIdAdmin;
    }

    public javax.swing.JTextField getTxtNamaAdmin() {
        return tfNamaAdmin;
    }

    public javax.swing.JTextField getTxtNikAdmin() {
        return tfNikAdmin;
    }

    public javax.swing.JTextField getTxtNoHpAdmin() {
        return tfNoHpAdmin;
    }

    public javax.swing.JPasswordField getTxtPasswordAdmin() {
        return tfPasswordAdmin;
    }


    public javax.swing.JTextField getTxtUsernameAdmin() {
        return tfUsernameAdmin;
    }
    
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getSourcePath() {
        return sourcePath;
    }

    public void setSourcePath(String sourcePath) {
        this.sourcePath = sourcePath;
    }

    public String getDestPath() {
        return destPath;
    }

    public void setDestPath(String destPath) {
        this.destPath = destPath;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        tfNamaAdmin = new javax.swing.JTextField();
        tfEmailAdmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbJenisKelamin = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfIdAdmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNoHpAdmin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNikAdmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAlamatAdmin = new javax.swing.JTextArea();
        tfUsernameAdmin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfPasswordAdmin = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        dcTglLahir = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaValidation = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 88, -1));
        getContentPane().add(tfNamaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 114, 184, -1));
        getContentPane().add(tfEmailAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 343, 184, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setText("NUSA BANK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 259, 61));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 79, -1, -1));

        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 117, -1, -1));

        cmbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Choose -", "Male", "Female" }));
        getContentPane().add(cmbJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 305, 184, -1));

        jLabel4.setText("GENDER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 311, -1, -1));

        jLabel5.setText("EMAIL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 349, -1, -1));
        getContentPane().add(tfIdAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 76, 184, -1));

        jLabel7.setText("PHONE NUMBER");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 387, 67, -1));
        getContentPane().add(tfNoHpAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 381, 184, -1));

        jLabel8.setText("NUMBER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 191, -1, -1));
        getContentPane().add(tfNikAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 188, 184, -1));

        jLabel9.setText("ADDRESS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 419, 67, -1));

        tfAlamatAdmin.setColumns(20);
        tfAlamatAdmin.setRows(5);
        jScrollPane1.setViewportView(tfAlamatAdmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 419, 184, 57));
        getContentPane().add(tfUsernameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 226, 184, -1));

        jLabel11.setText("NICKNAME");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 229, 67, -1));

        jLabel12.setText("PASSWORD");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 273, 67, -1));
        getContentPane().add(tfPasswordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 267, 180, -1));

        jLabel14.setText("DATE OF BIRTH");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 496, 76, -1));

        dcTglLahir.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dcTglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 494, 184, -1));

        txtAreaValidation.setBackground(new java.awt.Color(0, 0, 0));
        txtAreaValidation.setColumns(20);
        txtAreaValidation.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        txtAreaValidation.setForeground(new java.awt.Color(255, 102, 102));
        txtAreaValidation.setRows(5);
        txtAreaValidation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Validation Messages", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N
        txtAreaValidation.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtAreaValidation.setEnabled(false);
        jScrollPane3.setViewportView(txtAreaValidation);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 550, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        //cma.insert();
        cma.validateForm(true);
        //cma.reset();
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbJenisKelamin;
    private com.toedter.calendar.JDateChooser dcTglLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea tfAlamatAdmin;
    private javax.swing.JTextField tfEmailAdmin;
    private javax.swing.JTextField tfIdAdmin;
    private javax.swing.JTextField tfNamaAdmin;
    private javax.swing.JTextField tfNikAdmin;
    private javax.swing.JTextField tfNoHpAdmin;
    private javax.swing.JPasswordField tfPasswordAdmin;
    private javax.swing.JTextField tfUsernameAdmin;
    private javax.swing.JTextArea txtAreaValidation;
    // End of variables declaration//GEN-END:variables

    

    

    
}
