/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nusaregex.view;


import com.toedter.calendar.JDateChooser;
import com.nusaregex.controller.CManageAdmin;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
//import com.nusabank.view.viewAdmin.ViewMenuAdmin;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author ANDI DWI SAPUTRO
 */
public class ViewManageAdmin extends javax.swing.JFrame {

    private CManageAdmin cma;
    /**
     * Creates new form ViewManageAdmin
     */
    private String fileName;
    private String sourcePath;
    private String destPath;
    
    public ViewManageAdmin() {
        initComponents();
        cma = new CManageAdmin(this);
        cma.bindingTable();
        dcTglLahir.setDate(new Date());
        todayDateInit();
    }
    
    public void todayDateInit() {
        lbTodayDate.setText(LocalDateTime.now()
                .format(DateTimeFormatter.ofPattern("dd-MMMM-yyyy")));
    }
    
    public JTextArea getTxtAreaValidation() {
        return txtAreaValidation;
    }

    public JDateChooser getDcTglLahir() {
        return dcTglLahir;
    }
    
    public javax.swing.JComboBox<String> getCmbCategory() {
        return cmbCategory;
    }

    public javax.swing.JComboBox<String> getCmbJenisKelamin() {
        return cmbJenisKelamin;
    }

    public javax.swing.JTable getTableAdmin() {
        return tableAdmin;
    }

    public javax.swing.JTextArea getTxtAlamatAdmin() {
        return tfAlamatAdmin;
    }

    public javax.swing.JTextField getTxtEmailAdmin() {
        return tfEmailAdmin;
    }

    public javax.swing.JTextField getTxtIdAdmin() {
        return tfIdAdmin;
    }

    public javax.swing.JTextField getTxtNamaAdmin() {
        return tfNamaAdmin;
    }

    public javax.swing.JTextField getTxtNikAdmin() {
        return tfNikAdmin;
    }

    public javax.swing.JTextField getTxtNoHpAdmin() {
        return tfNoHpAdmin;
    }

    public javax.swing.JPasswordField getTxtPasswordAdmin() {
        return tfPasswordAdmin;
    }

    public javax.swing.JTextField getTxtPhotoAdminPath() {
        return tfPhotoAdminPath;
    }

    public javax.swing.JTextField getTxtSearch() {
        return tfSearch;
    }

    public javax.swing.JTextField getTxtUsernameAdmin() {
        return tfUsernameAdmin;
    }
    
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getSourcePath() {
        return sourcePath;
    }

    public void setSourcePath(String sourcePath) {
        this.sourcePath = sourcePath;
    }

    public String getDestPath() {
        return destPath;
    }

    public void setDestPath(String destPath) {
        this.destPath = destPath;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsert = new javax.swing.JButton();
        tfNamaAdmin = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        tfEmailAdmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbJenisKelamin = new javax.swing.JComboBox<>();
        lbTodayDate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAdmin = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        tfIdAdmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNoHpAdmin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNikAdmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAlamatAdmin = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        tfUsernameAdmin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnBrowsePhoto = new javax.swing.JButton();
        tfPhotoAdminPath = new javax.swing.JTextField();
        tfPasswordAdmin = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        dcTglLahir = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaValidation = new javax.swing.JTextArea();
        btnRefresh = new javax.swing.JButton();
        lbViewPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 573, 88, -1));
        getContentPane().add(tfNamaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 114, 184, -1));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 573, 88, -1));
        getContentPane().add(tfEmailAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 343, 184, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setText("NUSA BANK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 259, 61));

        jLabel2.setText("ID ADMIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 79, -1, -1));

        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 117, -1, -1));

        cmbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Choose -", "Male", "Female" }));
        getContentPane().add(cmbJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 305, 184, -1));

        lbTodayDate.setText("TGL");
        getContentPane().add(lbTodayDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 112, -1));

        jScrollPane2.setAutoscrolls(true);

        tableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAdmin.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableAdmin);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 155, 610, 270));

        jLabel4.setText("GENDER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 311, -1, -1));

        jLabel5.setText("EMAIL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 349, -1, -1));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 88, -1));
        getContentPane().add(tfIdAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 76, 184, -1));

        jLabel7.setText("PHONE NO.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 387, 67, -1));
        getContentPane().add(tfNoHpAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 381, 184, -1));

        jLabel8.setText("NIK");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 191, -1, -1));
        getContentPane().add(tfNikAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 188, 184, -1));

        jLabel9.setText("ADDRESS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 419, 67, -1));

        tfAlamatAdmin.setColumns(20);
        tfAlamatAdmin.setRows(5);
        jScrollPane1.setViewportView(tfAlamatAdmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 419, 184, 57));

        jLabel10.setText("Category:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 68, -1, -1));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NAME", "NIK", "USERNAME", "GENDER", "EMAIL", "PHONE_NO", "ADDRESS" }));
        getContentPane().add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 90, 103, -1));
        getContentPane().add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 122, 275, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 121, -1, -1));

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 573, -1, -1));
        getContentPane().add(tfUsernameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 226, 184, -1));

        jLabel11.setText("USERNAME");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 229, 67, -1));

        jLabel12.setText("PASSWORD");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 273, 67, -1));

        jLabel13.setText("PHOTO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 541, 76, -1));

        btnBrowsePhoto.setText("...");
        btnBrowsePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsePhotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrowsePhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 532, -1, -1));
        getContentPane().add(tfPhotoAdminPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 532, 134, 23));
        getContentPane().add(tfPasswordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 267, 140, -1));

        jLabel14.setText("D.o.B");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 496, 76, -1));

        dcTglLahir.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dcTglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 494, 184, -1));

        txtAreaValidation.setBackground(new java.awt.Color(0, 0, 0));
        txtAreaValidation.setColumns(20);
        txtAreaValidation.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        txtAreaValidation.setForeground(new java.awt.Color(255, 102, 102));
        txtAreaValidation.setRows(5);
        txtAreaValidation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Validation Messages", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N
        txtAreaValidation.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        txtAreaValidation.setEnabled(false);
        jScrollPane3.setViewportView(txtAreaValidation);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 444, 620, 150));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        lbViewPassword.setText("view");
        lbViewPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbViewPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbViewPasswordMouseExited(evt);
            }
        });
        getContentPane().add(lbViewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        cma.delete();
        cma.bindingTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBrowsePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsePhotoActionPerformed
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        // invoke the showsOpenDialog function to show the open dialog 
        int r = j.showOpenDialog(null);
        if (r == JFileChooser.APPROVE_OPTION) {
            this.setFileName(j.getSelectedFile().getName());
            this.setSourcePath(j.getSelectedFile().getAbsolutePath());
            tfPhotoAdminPath.setText(this.getSourcePath());
        }
    }//GEN-LAST:event_btnBrowsePhotoActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        //cma.insert();
        cma.validateForm(true);
        cma.bindingTable();
        //cma.reset();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //cma.update();
        cma.validateForm(false);
        cma.bindingTable();
        //cma.reset();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cma.reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        cma.getData();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tableAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdminMouseClicked
        cma.getDataField();
    }//GEN-LAST:event_tableAdminMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        cma.bindingTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void lbViewPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbViewPasswordMouseEntered
        tfPasswordAdmin.setEchoChar((char)0);
    }//GEN-LAST:event_lbViewPasswordMouseEntered

    private void lbViewPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbViewPasswordMouseExited
        tfPasswordAdmin.setEchoChar('\u25cf');
    }//GEN-LAST:event_lbViewPasswordMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewManageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewManageAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowsePhoto;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbJenisKelamin;
    private com.toedter.calendar.JDateChooser dcTglLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbTodayDate;
    private javax.swing.JLabel lbViewPassword;
    private javax.swing.JTable tableAdmin;
    private javax.swing.JTextArea tfAlamatAdmin;
    private javax.swing.JTextField tfEmailAdmin;
    private javax.swing.JTextField tfIdAdmin;
    private javax.swing.JTextField tfNamaAdmin;
    private javax.swing.JTextField tfNikAdmin;
    private javax.swing.JTextField tfNoHpAdmin;
    private javax.swing.JPasswordField tfPasswordAdmin;
    private javax.swing.JTextField tfPhotoAdminPath;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfUsernameAdmin;
    private javax.swing.JTextArea txtAreaValidation;
    // End of variables declaration//GEN-END:variables

    

    

    
}
